### ISSUE TITLE
dbFirst 采用自定义模板生成的Model 如何迁移 

### ISSUE THREAD

**Issue by li61609** [dotnet/EntityFramework.Docs.zh-cn#62]
即生成的实体model继承我自己定义的基类或接口
![image](https://user-images.githubusercontent.com/11290133/74910988-abf14f00-53f6-11ea-9727-86ccdafd45c8.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 422e4c63-a5c0-76ef-b30d-5e6ed7a32fe6
* Version Independent ID: 56cadf01-60b9-a9e4-919c-efbb894cabdb
* Content: [从 EF6 迁移到 EF Core-移植基于 EDMX 的模型-EF](https://docs.microsoft.com/zh-cn/ef/efcore-and-ef6/porting/port-edmx#feedback)
* Content Source: [entity-framework/efcore-and-ef6/porting/port-edmx.md](https://github.com/aspnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/efcore-and-ef6/porting/port-edmx.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @li61609
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@li61609，
再次感谢你的评论。
很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。
顺祝商祺！
Microsoft DOCS 国际团队
