### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by zzwind** [dotnet/EntityFramework.Docs.zh-cn#63]
安装工具那里第一行翻译错误
EF Core 1。x
应该为
EF Core 3.x

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core 工具参考（.NET CLI）-EF Core](https://docs.microsoft.com/zh-cn/ef/core/miscellaneous/cli/dotnet#feedback)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/dotnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by srvbpigh** [comment]
Hello, @zzwind
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@zzwind

感谢你的发布内容。

当前不接受有关机器翻译内容的翻译问题的发布内容。

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。

非常感谢你的支持。

Microsoft DOCS 全球体验团队
