### ISSUE TITLE
2处演示代码错误

### ISSUE THREAD

**Issue by heroxxCN** [dotnet/EntityFramework.Docs.zh-cn#65]
using (var context = new EntitySplittingEntities())
    {
        var person = new Person
        {
            FirstName = "John",
            LastName = "Doe",
            Email = "john@example.com",
            Phone = "555-555-5555"
        };

        context.People.Add(person);
        context.SaveChanges();

        foreach (var item in context.People)
        {
            Console.WriteLine(item.FirstName);
        }
    }

上述代码中两处context.People应该改为context.Person

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6484e79b-a6d1-4b2a-eb4a-8c3db41b07bb
* Version Independent ID: 4f869927-97ed-8a4b-572a-faa6708016f7
* Content: [设计器实体拆分-EF6](https://docs.microsoft.com/zh-cn/ef/ef6/modeling/designer/entity-splitting)
* Content Source: [entity-framework/ef6/modeling/designer/entity-splitting.md](https://github.com/dotnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/ef6/modeling/designer/entity-splitting.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @heroxxCN
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/EntityFramework.Docs #2189](https://github.com/dotnet/EntityFramework.Docs/issues/2189) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@heroxxCN 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/EntityFramework.Docs/issues/2189。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
