### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by jjwly** [dotnet/EntityFramework.Docs.zh-cn#67]
上下文通常在 Startup.cs 中进行配置，其中的连接字符串是从配置中读取的。 请注意，GetConnectionString() 方法查找其键 ConnectionStrings:<connection string name>的配置值。 需要导入 **Microsoft extension . 配置命名空间**才能使用此扩展方法。

应为

上下文通常在 Startup.cs 中进行配置，其中的连接字符串是从配置中读取的。 请注意，GetConnectionString() 方法查找其键 ConnectionStrings:<connection string name>的配置值。 需要导入 **Microsoft extension.Configuration命名空间**才能使用此扩展方法。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [连接字符串-EF Core](https://docs.microsoft.com/zh-cn/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/dotnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @jjwly
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@jjwly

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。  

非常感谢你的支持。 

Microsoft DOCS 全球体验团队
