### ISSUE TITLE
对术语定义上下文统一的建议

### ISSUE THREAD

**Issue by SmRiley** [dotnet/EntityFramework.Docs.zh-cn#72]
在术语定义的代码描述中,"相关实体(Dependent entity)"被翻译成"依赖实体"(如图),我觉得这或许会让新手觉得困惑.建议统一上下文的术语定义.
![image](https://user-images.githubusercontent.com/45205313/81192180-7d921180-8fec-11ea-94f3-6b4a6d4bcf01.png)

**Comment by srvbpigh** [comment]
Hello, @SmRiley
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@SmRiley

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

**No URL**

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by SmRiley** [comment]
不好意思,我没有提供具体的URL.
我所反馈的页面为:https://github.com/dotnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/modeling/relationships.md
问题为**术语定义**的上下文描述统一的建议:如Dependent entity在定义中被翻译为**相关实体**,下文的描述却被翻译为"依赖实体",这或许会让新手感到困惑.

**Comment by SmRiley** [comment]
已发送拉取请求,关闭此issues

**Comment by SmRiley** [comment]
pull Request被拒绝.Reopen

**Comment by CeciAc** [comment]
你好，@SmRiley

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。 

非常感谢你的支持。 

Microsoft DOCS 全球体验团队
