### ISSUE TITLE
两个sqlserver数据库如何保证事务性

### ISSUE THREAD

**Issue by bxjg1987** [dotnet/EntityFramework.Docs.zh-cn#74]
之前.net framework版本中可以使用TransactionScope来实现，.net core 3.x版本中有什么方案吗？

**Comment by srvbpigh** [comment]
Hello, @bxjg1987
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/EntityFramework.Docs #2462](https://github.com/dotnet/EntityFramework.Docs/issues/2462) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@bxjg1987 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/EntityFramework.Docs/issues/2462。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
