### ISSUE TITLE
文档中的文字错误

### ISSUE THREAD

**Issue by Liaille** [dotnet/EntityFramework.Docs.zh-cn#75]
[在此处输入反馈]
如果只有一个导航属性，则和的无参数重载 WithOne WithMany 。这一句中的“则和的”使人无法理解，是否表达的是“则使用”
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [关系-EF Core](https://docs.microsoft.com/zh-cn/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
Dup of #83
