### ISSUE TITLE
机翻中文语法错误

### ISSUE THREAD

**Issue by jaywhen** [dotnet/EntityFramework.Docs.zh-cn#83]
在标题：**单个导航属性** 下：
原句英文为：
> If you only have one navigation property then there are parameterless overloads of `WithOne` and `WithMany`

原句机翻中文为:
> 如果只有一个导航属性，则和的无参数重载 `WithOne` `WithMany` 。

翻译应修改为:
如果只有一个导航属性，则 `WithOne` 和 `WithMany` 会发生无参数重载。
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [关系-EF Core](https://docs.microsoft.com/zh-cn/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#feedback)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
> Under the title: **single navigation attribute** : the
> original sentence in English is:
> 
> > If you only have one navigation property then there are parameterless overloads of `WithOne` and `WithMany`
> 
> The original sentence machine translated into Chinese is:
> 
> > If there is only one navigation attribute, then the parameterless overload of the sum `WithOne` `WithMany`.
> 
> ## Translation should be amended as follows:
> if only a navigation attribute, `WithOne`and `WithMany`will not happen parameters overloaded.

This would be a good one to fix. @JasonCard  is there someone I can notify?

**Comment by Rick-Anderson** [comment]
Dup of #75

**Comment by JasonCard** [comment]
@jaywhen @Rick-Anderson Thank you for flagging this issue. I'm following up on fixing this Machine Translation issue with human translation for this particular sentence.

**Comment by jaywhen** [comment]
> @jaywhen @Rick-Anderson Thank you for flagging this issue. I'm following up on fixing this Machine Translation issue with human translation for this particular sentence.

nice！

**Comment by JasonCard** [comment]
@jaywhen This is now fixed :)
如果只有一个导航属性，则 WithOne 和 WithMany 会发生无参数重载。
